### ISSUE TITLE
Fix spelling errors and code style

### ISSUE THREAD

**Issue by Artur2** [Saritasa/Unity3DTools#1]
https://github.com/Saritasa/Unity3DTools/blob/master/Editor/FindReferencesInProject/FindReferencesInProject.cs#L139 - what means "b" ?

DependenciesCash - DependenciesCache

**Comment by skondratov** [comment]
Hi Alexander (@arbuznikov ),

Please also add comments to class and methods.

**Comment by skondratov** [comment]
@arbuznikov 
I added TODO's, please fix them asap.

**Comment by arbuznikov** [comment]
Fixed
